version: '3.8'

services:
  db:
    image: mariadb:10.7
    container_name: glpi-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi_user
      MYSQL_PASSWORD: glpi_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - glpi-network

  glpi:
    image: diouxx/glpi
    container_name: glpi
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - glpi_data:/var/www/html
    networks:
      - glpi-network

volumes:
  db_data:
  glpi_data:

networks:
  glpi-network:
