version: '3.8'

services:
  glpi-db:
    image: mariadb:10.5
    container_name: glpi-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    volumes:
      - glpi-db-data:/var/lib/mysql
    networks:
      - glpi-network

  glpi:
    image: diouxx/glpi
    container_name: glpi
    environment:
      DB_HOST: glpi-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: glpi
      TZ: America/Sao_Paulo
    ports:
      - "8000:80"  # Trocar as portas para as disponíveis na VM!!!
    networks:
      - glpi-network
    depends_on:
      - glpi-db

volumes:
  glpi-db-data:

networks:
  glpi-network:
    driver: bridge
