version: '3.8'

services:
  zabbix-db:
    image: postgres:15
    container_name: zabbix-db
    environment:
      POSTGRES_DB: nocs
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: America/Sao_Paulo
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"  # Trocar as portas para as disponíveis na VM!!!
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: America/Sao_Paulo
    depends_on:
      - zabbix-server
    ports:
      - "7000:8080"  # Trocar as portas para as disponíveis na VM!!!  (Interface Web)
    networks:
      - zabbix-network

volumes:
  zabbix-db-data:

networks:
  zabbix-network:
    driver: bridge
